### ISSUE TITLE
Definir modelo para Task

### ISSUE THREAD

**Issue by gustavomleal** [Monkey-Judge/backend#18]
{
id: int,
id_judge: int,
original_id: string,
title: string,
memory_limit: string,
time_limit: int,
statement: string
input: string,
output: string,
notes: string,
pdf_link: string,
source_link: string,
}

**Comment by rafaelcsva** [comment]
esse time_limit vai ser inteiro mesmo ?

> {
> id: int,
> id_judge: int,
> original_id: string,
> title: string,
> memory_limit: string,
> time_limit: int,
> statement: string
> input: string,
> output: string,
> notes: string,
> pdf_link: string,
> source_link: string,
> }

time limit vai ser inteiro mesmo ?
