### ISSUE TITLE
Definir end-point para registrar usuarios

### ISSUE THREAD

**Issue by rafaelcsva** [Monkey-Judge/backend#2]
response: {
 code: 123,
 msg: "..."
}

**Comment by Pkataki** [comment]
Qual será a rota? Já é para implementar a encriptação da senha?

**Comment by rafaelcsva** [comment]
pode ser a rota /users/register, se quiser pode implementar a encriptação, só coloca o algoritmo que usou para quem for fazer a issue [https://github.com/Monkey-Judge/backend/issues/6](#6 ) depois

**Comment by leandrovianna** [comment]
> pode ser a rota /users/register, se quiser pode implementar a encriptação, só coloca o algoritmo que usou para quem for fazer a issue [https://github.com/Monkey-Judge/backend/issues/6](#6) depois
O que você quis dizer com encriptação?

**Comment by rafaelcsva** [comment]
> > pode ser a rota /users/register, se quiser pode implementar a encriptação, só coloca o algoritmo que usou para quem for fazer a issue [https://github.com/Monkey-Judge/backend/issues/6](#6) depois
> 
> O que você quis dizer com encriptação?

hash simples de string no password

**Comment by Pkataki** [comment]
Somente a hash mesmo? ou usar SALT para encriptação?


> > > pode ser a rota /users/register, se quiser pode implementar a encriptação, só coloca o algoritmo que usou para quem for fazer a issue [https://github.com/Monkey-Judge/backend/issues/6](#6) depois
> > 
> > 
> > O que você quis dizer com encriptação?
> 
> hash simples de string no password

Somente a hash? Ou utilizar Salt?

**Comment by Pkataki** [comment]
> > > pode ser a rota /users/register, se quiser pode implementar a encriptação, só coloca o algoritmo que usou para quem for fazer a issue [https://github.com/Monkey-Judge/backend/issues/6](#6) depois
> > 
> > 
> > O que você quis dizer com encriptação?
> 
> hash simples de string no password

Somente a hash? Ou utilizar Salt?

**Comment by Pkataki** [comment]
No link abaixo há um exemplo de end-to-end testing, seria este para testar o registro de usuários?
link: https://dev.to/nedsoft/testing-nodejs-express-api-with-jest-and-supertest-1km6
