### ISSUE TITLE
Usar Javascript codestyle

### ISSUE THREAD

**Issue by leandrovianna** [Monkey-Judge/backend#8]
Ideia: Configurar pre-commit hook para rodar JSLint nos arquivos que estão no commit.

Fonte: https://stackoverflow.com/a/7385947/3889721

**Comment by Pkataki** [comment]
Encontrei uma alternativa aparentemente melhor.
link: https://standardjs.com/

**Comment by leandrovianna** [comment]
@Pkataki é uma alternativa melhor mesmo. É mais fácil de configurar. Podemos usar um [pre-commit hook](https://standardjs.com/#is-there-a-git-pre-commit-hook). As [regras de estilo](https://standardjs.com/rules.html) são boas também.
